spring.application.name=CRMTicketing
server.port=8080
db.driver-class-name=com.mysql.cj.jdbc.Driver
db.username=root
db.password=root
db.url=jdbc:mysql://localhost:3306/CRM

spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect

logging.level.org.hibernate.SQL=DEBUG
logging.level.org.hibernate.type.descriptor.sql=TRACE